# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ratlas}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Cooper"]
  s.date = %q{2011-04-06}
  s.description = %q{Rutlas allows you to consume to the Atlas api without getting your hands dirty}
  s.email = %q{daniel@14lines.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/patches/string.rb",
    "lib/ratlas.rb",
    "lib/ratlas/content.rb",
    "lib/ratlas/discover.rb",
    "lib/ratlas/query.rb",
    "lib/ratlas/queryable.rb",
    "lib/ratlas/response.rb",
    "lib/ratlas/schedule.rb",
    "lib/ratlas/search.rb",
    "ratlas.gemspec",
    "spec/container_spec.rb",
    "spec/fixtures/content.json",
    "spec/live_container_spec.rb",
    "spec/ratlas_spec.rb"
  ]
  s.homepage = %q{http://github.com/daniel_cooper/ratlas}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{A Atlas api Ruby client}
  s.test_files = [
    "spec/container_spec.rb",
    "spec/live_container_spec.rb",
    "spec/ratlas_spec.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<hashie>, [">= 0"])
      s.add_development_dependency(%q<addressable>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<hashie>, [">= 0"])
      s.add_dependency(%q<addressable>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<hashie>, [">= 0"])
    s.add_dependency(%q<addressable>, [">= 0"])
  end
end

